apiVersion: v1
kind: Service
metadata:
  name: payload-service
  labels:
    app: payload
spec:
  type: ClusterIP
  selector:
    app: payload
  ports:
    - port: 80
      targetPort: 3001
      protocol: TCP
      name: http